### PR TITLE
fix lost:comma

### PR DESCRIPTION
**Pull request by ReineChiu**

### CODE REVIEW

**Comment by ReineChiu** [comment]
WH03045 邱逸萍

I found I lost a colon in attraction.py and I wrote wrong commit (comma).
The point is I need Review required to merge my branch.
Thank you!

**Review by cwpeng — DISMISSED** [review]
OK. Good Details.

**Comment by ReineChiu** [comment]
WH03045 邱逸萍
Discord ： shawpa

Last week I found another error and corrected it,
so I PR them together.

http://3.217.7.0:3000

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should close category block after choosing one of them.
2. Layout issue: we should keep layout in center 1200px, align content to left or right, when screen width>1200px

**Comment by ReineChiu** [comment]
WH03045 邱逸萍
Discord ： shawpa

Fix the problem：
1. Close category block after choosing .
2.Keep layout in center 1200px (when screen width>1200px).

http://3.217.7.0:3000

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but I just notice that If I click on blank area of category block, keyword input will fill with all category names.

**Comment by ReineChiu** [comment]
WH03045 邱逸萍
Discord ： shawpa

Fix the problem：
click on blank area of category block, keyword input all category names.


http://3.217.7.0:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
