### PR TITLE
GUIDE - part7

### PR DESCRIPTION
**Pull request by ReineChiu**
WH03045 邱逸萍
discord：shawpa

http://3.217.7.0:3000

1. Use Connection Pool.
2. Complete Confidential information.
   (hash user password)
3. Complete web page but not very good.(lack of beauty)
4. part of data verification.
5. member page.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot book because your page always say "選擇 2023-1-1 之後的日期"

**Comment by ReineChiu** [comment]
WH03045 邱逸萍
discord：shawpa

http://3.217.7.0:3000

Fix book date

**Review by cwpeng — APPROVED** [review]
It's OK. Many improvements. :)

**Comment by cwpeng** [comment]
Happy new year.

**Pull request merged**
